Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,45 +1,214 @@
-name: Actions 😎
+name: GameCI Template 🎮
 
-on: [push, pull_request]
+on: push
+
+env:
+  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
 
 jobs:
-  build:
-    name: Build my project ✨
+  checkLicense:
+    name: Check for the Unity license ☑️
     runs-on: ubuntu-latest
     steps:
-      # Checkout
-      - name: Checkout repository
-        uses: actions/checkout@v2
-        with:
-          lfs: true
+      - name: Fail - No license ☠️
+        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
+        run: exit 1
 
-      # Cache
-      - uses: actions/cache@v2
-        with:
-          path: Library
-          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
-          restore-keys: |
-            Library-
+ testRunner:
+   needs: checkLicense
+   name: Test all modes 📝
+   runs-on: ubuntu-latest
+   steps:
+     - name: Checkout code
+       uses: actions/checkout@v2
 
-      # Test
-      - name: Run tests
-        uses: game-ci/unity-test-runner@v2
-        env:
-          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
-        with:
-          githubToken: ${{ secrets.GITHUB_TOKEN }}
+     - name: Create LFS file list
+       run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
 
-      # Build
-      - name: Build project
-        uses: game-ci/unity-builder@v2
-        env:
-          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
-        with:
-          targetPlatform:           
-            StandaloneWindows64 # Build a Windows 64-bit standalone.
+     - name: Restore LFS cache
+       uses: actions/cache@v2
+       id: lfs-cache
+       with:
+         path: .git/lfs
+         key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
 
-      # Output
-      - uses: actions/upload-artifact@v2
-        with:
-          name: Build
-          path: build
+     - name: Git LFS Pull
+       run: |
+         git lfs pull
+         git add .
+         git reset --hard
+
+     - name: Restore Library cache
+       uses: actions/cache@v2
+       with:
+         path: Library
+         key: Library-test-project
+         restore-keys: |
+           Library-test-project-
+           Library-
+
+     - uses: webbertakken/unity-test-runner@v2
+       id: testRunner
+       with:
+         testMode: all
+
+     - uses: actions/upload-artifact@v2
+       with:
+         name: Test results (all modes)
+         path: ${{ steps.testRunner.outputs.artifactsPath }}
+#
+#  buildWebGL:
+#    needs: testRunner
+#    name: Build for WebGL 🖥️
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#
+#      - name: Create LFS file list
+#        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
+#
+#      - name: Restore LFS cache
+#        uses: actions/cache@v2
+#        id: lfs-cache
+#        with:
+#          path: .git/lfs
+#          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
+#
+#      - name: Git LFS Pull
+#        run: |
+#          git lfs pull
+#          git add .
+#          git reset --hard
+#
+#      - name: Restore Library cache
+#        uses: actions/cache@v2
+#        with:
+#          path: Library
+#          key: Library-build-WebGL
+#          restore-keys: |
+#            Library-build-
+#            Library-
+#
+#      - uses: webbertakken/unity-builder@v2
+#        with:
+#          targetPlatform: WebGL
+#
+#      - uses: actions/upload-artifact@v2
+#        with:
+#          name: build-WebGL
+#          path: build/WebGL
+#
+ buildWindows:
+   needs: testRunner
+   name: Build for Windows 🖥️
+   runs-on: ubuntu-latest
+   strategy:
+     fail-fast: false
+   steps:
+     - name: Checkout code
+       uses: actions/checkout@v2
+
+     - name: Create LFS file list
+       run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
+
+     - name: Restore LFS cache
+       uses: actions/cache@v2
+       id: lfs-cache
+       with:
+         path: .git/lfs
+         key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
+
+     - name: Git LFS Pull
+       run: |
+         git lfs pull
+         git add .
+         git reset --hard
+
+     - name: Restore Library cache
+       uses: actions/cache@v2
+       with:
+         path: Library
+         key: Library-build-StandaloneWindows64
+         restore-keys: |
+           Library-build-
+           Library-
+
+     - uses: webbertakken/unity-builder@v2
+       with:
+         targetPlatform: StandaloneWindows64
+
+     - uses: actions/upload-artifact@v2
+       with:
+         name: build-StandaloneWindows64
+         path: build/StandaloneWindows64
+#
+#  buildAndroid:
+#    needs: testRunner
+#    name: Build for Android 📱
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#
+#      - name: Create LFS file list
+#        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
+#
+#      - name: Restore LFS cache
+#        uses: actions/cache@v2
+#        id: lfs-cache
+#        with:
+#          path: .git/lfs
+#          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
+#
+#      - name: Git LFS Pull
+#        run: |
+#          git lfs pull
+#          git add .
+#          git reset --hard
+#
+#      - name: Restore Library cache
+#        uses: actions/cache@v2
+#        with:
+#          path: Library
+#          key: Library-build-Android
+#          restore-keys: |
+#            Library-build-
+#            Library-
+#
+#      - uses: webbertakken/unity-builder@v2
+#        with:
+#          targetPlatform: Android
+#
+#      - uses: actions/upload-artifact@v2
+#        with:
+#          name: build-Android
+#          path: build/Android
+#
+#
+#  deployPages:
+#    needs: buildWebGL
+#    name: Deploy to Github Pages 🚀
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v2
+#
+#      - uses: actions/download-artifact@v2
+#        with:
+#          name: build-WebGL
+#          path: build
+#
+#      - name: Display structure of root files
+#        run: ls -R
+#        working-directory: build/WebGL
+#
+#      - name: Deploy 🚀
+#        uses: JamesIves/github-pages-deploy-action@4.1.4
+#        with:
+#          branch: gh-pages
+#          folder: build/WebGL
